### ISSUE TITLE
Question: Make background transparent?

### ISSUE THREAD

**Issue by salsa-barbecue** [Fabiz/PeakFinder-API#1]
How can I change the background of the mountain projetion to transparent? I can't see it in the options but i need it

**Comment by Fabiz** [comment]
This is currently not possible. But I think I can add such an option. Out of curiosity: can you describe what you like to do with the transparent background?

**Comment by salsa-barbecue** [comment]
I need to use my default background color and maybe in the future use the view as a layer on a georeferenced image

**Comment by Fabiz** [comment]
I did some experiments with a transparent background. Unfortunately this was on some browsers not working correctly .

So I decided to skip transparency and add just the option to set the background/sky color. 
See here for the result: https://fabiz.github.io/PeakFinder-API/basicexample_canvas_bgcolor.html

I hope this works for your use case.

**Comment by Fabiz** [comment]
Added option to set the background color.

**Comment by silvio-barbotto** [comment]
Thanks for the reply, I tryed to use the #RRGGBBAA hex value for the color but it seems there is still a black layer in background, can you remove it?

**Comment by Fabiz** [comment]
Please use #RRGGBB instead of #RRGGBBAA. 
I'll make the color parser more tolerant in a next update.
