### ISSUE TITLE
Demo page 

### ISSUE THREAD

**Issue by haldo98** [Fabiz/PeakFinder-API#15]
There is a misplacement of the corner buttons also in the demo page

https://fabiz.github.io/PeakFinder-API/basicexample_canvas.html

the canvas is too big for the frame and the buttons are partially hidden in the corner

**Comment by Fabiz** [comment]
Hi Haldo

Thanks for the error report. I just fixed this issue.

best regards 
Fabio

**Comment by Fabiz** [comment]
Fixed issue.
