### ISSUE TITLE
Getter for the altitude isn't working properly

### ISSUE THREAD

**Issue by salsa-barbecue** [Fabiz/PeakFinder-API#2]
The getter for the altitude value isn't working properly.
When I use `panel.azimut()` and `panel.fieldofview()` everything is alright but `panel.altitude()` throws this error

> peakfinder.1.0.min.js:1 Uncaught TypeError: this.wasm._getAltitude is not a function
> at PeakFinder.PanoramaPanel.altitude (peakfinder.1.0.min.js:1:1916)
> at HTMLDivElement.<anonymous> (visualizzazioneMappa.js?rb1iah:537:40)
> at HTMLDivElement.dispatch (jquery.min.js?v=3.6.0:2:43064)
> at HTMLDivElement.v.handle (jquery.min.js?v=3.6.0:2:41048)

**Comment by salsa-barbecue** [comment]
I analyzed the main [library](https://www.peakfinder.org/wasm/peakfinder.4.4.3.js) and I found the problem.
The function _getAltitude doesn't exists because there is a typo in the name.

>var **_getAltitide** = (Module["**_getAltitide**"] = function () {
>  return (**_getAltitide** = Module["**_getAltitide**"] =
>  Module["asm"]["Sj"]).apply(null, arguments);
>});
>var _setAltitude = (Module["_setAltitude"] = function () {
>  return (_setAltitude = Module["_setAltitude"] =
>  Module["asm"]["Tj"]).apply(null, arguments);
>});

**Comment by Fabiz** [comment]
Thanks a lot for the bug report. I've fixed this error. It should work correctly now.
