### ISSUE TITLE
REQUEST: Add some functionalities

### ISSUE THREAD

**Issue by salsa-barbecue** [Fabiz/PeakFinder-API#3]
Hi, I would like to know wether the following functionalities are going to be added or are already present in the API:
- Set the background to transparent
- Show the delta from the current position for the heights of the mountains
- Set height and distance to 2 differents units of measurement (ex. heights in feet and distance in Kilometers)

**Comment by Fabiz** [comment]
> Set the background to transparent
Setting the background to transparent is not possible. But setting a color works now.

> Show the delta from the current position for the heights of the mountains
Can you give me more details about the use case you have? 

> Set height and distance to 2 differents units of measurement (ex. heights in feet and distance in Kilometers)
Are there some countries with mixed units?

**Comment by salsa-barbecue** [comment]
I need to see the difference of height between the origin point (the one which latitude and longitude i use to set the canvas) and the points i see. I can't give away any details about the application I'm developing.
There are no countries that i know of but helicopter pilots use imperial for height and metric for distance.

**Comment by Fabiz** [comment]
How would select the 'points you see'? Do you know the coordinates of these points?
In this case you could use an elevation lookup api like: https://developers.google.com/maps/documentation/elevation/overview

I can add support for imperial-height and metric-distance in a future update.

**Comment by salsa-barbecue** [comment]
I don't use coordinates i need to look at the 3d projection of the mountains and use the telescope

**Comment by Fabiz** [comment]
> I don't use coordinates i need to look at the 3d projection of the mountains and use the telescope

Would it be helpful when I add functions to get the data from the telescope (coords, azi, alt, elevation, distance) and the current viewpoint (coords, elevation)? Then you can do the needed calculations on your side.

**Comment by salsa-barbecue** [comment]
Yes that would be perfect

**Comment by salsa-barbecue** [comment]
Hi, any news about these updates?

**Comment by Fabiz** [comment]
Hi Luca

I’m very sorry for the delay. I’ll add this functionality next week to the api. 

best regards 
Fabio

**Comment by salsa-barbecue** [comment]
Hi, thanks for the telescope functions, I can't see the function to get the current viewpoint elevation in the documentation though. Have you added it yet?

**Comment by Fabiz** [comment]
Hi Luca

I just added the function for getting the elevation from the current viewpoint.

best regards, Fabio

**Comment by salsa-barbecue** [comment]
Thank you
