### ISSUE TITLE
Feature request: set visibility range

### ISSUE THREAD

**Issue by zbooyek** [Fabiz/PeakFinder-API#4]
Hi,

would it be possible to set the (starting) visibility range via an API call? I'm using it to display a PeakFinder panorama side-by-side with my mountain panoramas.

BTW, great work,
sz

**Comment by Fabiz** [comment]
Thanks for the input. I just released a new version with this functionality. all the bestFabioAm 13.09.2022 um 21:24 schrieb zbooyek ***@***.***>:﻿
Hi,
would it be possible to set the (starting) visibility range via an API call? I'm using it to display a PeakFinder panorama side-by-side with my mountain panoramas.
BTW, great work,
sz

**Comment by zbooyek** [comment]
Hello Fabio, it's working fine, thank you very much!
