### ISSUE TITLE
Elevation getter not working

### ISSUE THREAD

**Issue by salsa-barbecue** [Fabiz/PeakFinder-API#5]
Hi, the function to get the elevation for the viewpoint always gives 0

**Comment by Fabiz** [comment]
Hi LucaI just released a fix. Can you check if its working correctly now, please?best regards FabioAm 27.09.2022 um 10:36 schrieb Luca Leone ***@***.***>:﻿
Hi, the function to get the elevation for the viewpoint always gives 0

**Comment by salsa-barbecue** [comment]
Yes solved thanks
